version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-ecr: circleci/aws-ecr@6.8.2
  aws-cli: circleci/aws-cli@1.0.0
  helm: circleci/helm@0.2.3

jobs:
  publish-latest-ecr:
    environment:
      IMAGE_NAME: hello-python
      AWS_REGION: us-east-1
      VERSION: 0.0.3-develop
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - helm/install-helm-client
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          repo: $IMAGE_NAME
          create-repo: true
          tag: $CIRCLE_BRANCH$CIRCLE_BUILD_NUM,latest,$VERSION-$CIRCLE_SHA1
          aws-access-key-id: ACCESS_KEY_ID_ENV_VAR_NAME
          aws-secret-access-key: SECRET_ACCESS_KEY_ENV_VAR_NAME
      - run:
          name: Publish chart
          command: ./deploy/publish_chart.sh
  publish-latest-dh:
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME .
      - run:
          name: Tag image to ship with branch and build num
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image to Docker Hub with branch and build num
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_ORG/$IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
      - run:
          name: Tag image to ship with latest tag
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub with latest tag
          command: |
            docker push $DOCKERHUB_ORG/$IMAGE_NAME:latest
  publish-branch-dh:
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME .
      - run:
          name: Tag image to ship with branch and build num
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image to Docker Hub with branch and build num
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest-ecr:
          filters:
            branches:
              only: 
               - master
  build-any:
    jobs:
      - publish-branch-dh:
          filters:
            branches:
              ignore: 
                - master
