version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  setup: &setup
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps: []
  build: &build
    <<: *setup
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME .
  publish: &publish
    <<: *setup
    steps:
      - setup_remote_docker
      - run:
          name: Tag image to ship
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
  latest: &latest
    <<: *setup
    steps:
      - run:
          name: Tag image to ship
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:$IMAGE_TAG
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_ORG/$IMAGE_NAME:$IMAGE_TAG
  publish-branch: &publish-branch
    <<: *build
    <<: *publish
  publish-latest:
    <<: *publish-branch
    <<: *latest
workflows:
  version: 2
  build-master:
    jobs:
      - publish-latest:
          filters:
            branches:
              only: master
  build-any:
    jobs:
      - publish-branch:
          filters:
            branches:
              ignore: 
                - master
