version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME .
  publish-latest:
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps:
      - setup_remote_docker
      - run:
          name: Tag image to ship
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:latest
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $DOCKERHUB_ORG/$IMAGE_NAME:latest
  publish-branch:
    environment:
      IMAGE_NAME: hello-python
    executor: python/default
    steps:
      - setup_remote_docker
      - run:
          name: Tag image to ship
          command: |
            docker tag $IMAGE_NAME $DOCKERHUB_ORG/$IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_BRANCH$CIRCLE_BUILD_NUM
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master
  build-any:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - master
      - publish-branch:
          requires:
            - build
          filters:
            branches:
              ignore: 
                - master
